import{a as w,S,i as l}from"./assets/vendor-73qhTu8_.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))n(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const s of r.addedNodes)s.tagName==="LINK"&&s.rel==="modulepreload"&&n(s)}).observe(document,{childList:!0,subtree:!0});function i(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function n(e){if(e.ep)return;e.ep=!0;const r=i(e);fetch(e.href,r)}})();const q="55677737-862d1a0c317a7b252ed3feed4",B="https://pixabay.com/api/";async function u(o,t){return(await w.get(B,{params:{key:q,q:o,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:15,page:t}})).data}const m=document.querySelector(".gallery"),f=document.querySelector(".loader"),p=document.querySelector(".load-more"),$=new S(".gallery a",{captions:!0,captionsData:"alt",captionDelay:250});function y(o){const t=o.map(({webformatURL:i,largeImageURL:n,tags:e,likes:r,views:s,comments:L,downloads:v})=>`
<li class="gallery-item">
  <a href="${n}">
    <img src="${i}" alt="${e}" />
  </a>
  <div class="info">
    <p><b>Likes</b>: ${r}</p>
    <p><b>Views</b>: ${s}</p>
    <p><b>Comments</b>: ${L}</p>
    <p><b>Downloads</b>: ${v}</p>
  </div>
</li>`).join("");m.insertAdjacentHTML("beforeend",t),$.refresh()}function M(){m.innerHTML=""}function g(){f.classList.add("is-visible")}function h(){f.classList.remove("is-visible")}function E(){p.classList.add("is-visible")}function d(){p.classList.remove("is-visible")}const O=document.querySelector(".form"),x=document.querySelector(".load-more");let c="",a=1,b=0;d();O.addEventListener("submit",async o=>{if(o.preventDefault(),c=o.target.elements["search-text"].value.trim(),!!c){a=1,M(),d(),g();try{const t=await u(c,a);if(t.hits.length===0){l.warning({message:"Sorry, there are no images matching your search query."});return}b=t.totalHits,y(t.hits),E()}catch{l.error({message:"Something went wrong."})}finally{h()}}});x.addEventListener("click",async()=>{a++,g();try{const o=await u(c,a);y(o.hits);const t=document.querySelector(".gallery-item").getBoundingClientRect();window.scrollBy({top:t.height*2,behavior:"smooth"}),a*15>=b&&(d(),l.info({message:"We're sorry, but you've reached the end of search results."}))}catch{l.error({message:"Error loading more images"})}finally{h()}});
//# sourceMappingURL=index.js.map
