import{a as S,S as q,i}from"./assets/vendor-73qhTu8_.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))l(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const a of r.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&l(a)}).observe(document,{childList:!0,subtree:!0});function c(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function l(e){if(e.ep)return;e.ep=!0;const r=c(e);fetch(e.href,r)}})();const B="55677737-862d1a0c317a7b252ed3feed4",$="https://pixabay.com/api/";async function f(o,t){return(await S.get($,{params:{key:B,q:o,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:15,page:t}})).data}const m=document.querySelector(".gallery"),y=document.querySelector(".loader"),p=document.querySelector(".load-more"),M=new q(".gallery a",{captions:!0,captionsData:"alt",captionDelay:250});function g(o){const t=o.map(({webformatURL:c,largeImageURL:l,tags:e,likes:r,views:a,comments:v,downloads:w})=>`
<li class="gallery-item">
  <a href="${l}">
    <img src="${c}" alt="${e}" />
  </a>
  <div class="info">
    <p><b>Likes</b>: ${r}</p>
    <p><b>Views</b>: ${a}</p>
    <p><b>Comments</b>: ${v}</p>
    <p><b>Downloads</b>: ${w}</p>
  </div>
</li>`).join("");m.insertAdjacentHTML("beforeend",t),M.refresh()}function E(){m.innerHTML=""}function h(){y.classList.add("is-visible")}function b(){y.classList.remove("is-visible")}function L(){p.classList.add("is-visible")}function n(){p.classList.remove("is-visible")}const O=document.querySelector(".form"),x=document.querySelector(".load-more");let d="",s=1,u=0;n();O.addEventListener("submit",async o=>{if(o.preventDefault(),d=o.target.elements["search-text"].value.trim(),!!d){s=1,E(),n(),h();try{const t=await f(d,s);if(t.hits.length===0){i.warning({message:"Sorry, there are no images matching your search query."});return}u=t.totalHits,g(t.hits),s*15<u?L():(n(),i.info({message:"We're sorry, but you've reached the end of search results."}))}catch{i.error({message:"Something went wrong."})}finally{b()}}});x.addEventListener("click",async()=>{s++,n(),h();try{const o=await f(d,s);g(o.hits);const t=document.querySelector(".gallery-item").getBoundingClientRect();window.scrollBy({top:t.height*2,behavior:"smooth"}),s*15<u?L():(n(),i.info({message:"We're sorry, but you've reached the end of search results."}))}catch{i.error({message:"Error loading more images"})}finally{b()}});
//# sourceMappingURL=index.js.map
